
-- Create your spells
local NewSpell = Aurora.SpellHandler.NewSpell

Aurora.SpellHandler.PopulateSpellbook({
    spells = {
        --DK
        AutoAttack                      = NewSpell(6603),
        RaiseDead                       = NewSpell(46585),
        MindFreeze                      = NewSpell(47528),
        DeathAndDecay                   = NewSpell(43265, {isSkillshot = true, radius = 8}),
        AntiMagicShell                  = NewSpell(48707),
        PathOfFrost                     = NewSpell(3714),
        AntiMagicZone                   = NewSpell(51052),
        DeathGrip                       = NewSpell(49576),
        RaiseAlly                       = NewSpell(61999),
        Asphyxiate                      = NewSpell(221562),
        RuneStrike                      = NewSpell(316239),
        DarkCommand                     = NewSpell(56222),
        DeathCoil                       = NewSpell(47541),
        DeathsAdvance                   = NewSpell(48265),
        DeathCharge                     = NewSpell(444347),
        IceboundFortitude               = NewSpell(48792),
        Lichborne                       = NewSpell(49039),
        Runeforging                     = NewSpell(53428),
        ChainsOfIce                     = NewSpell(45524),
        DeathStrike                     = NewSpell(49998),
        BlindingSleet                   = NewSpell(207167),
        ControlUndead                   = NewSpell(111673),
        SacrificialPact                 = NewSpell(327574),
        DeathPact                       = NewSpell(48743),
        WraithWalk                      = NewSpell(212552),
        SoulReaper                      = NewSpell(343294),

        --Frost
        RemorselessWinter               = NewSpell(196770),
        FrostStrike                     = NewSpell(49143),
        Obliterate                      = NewSpell(49020),
        HowlingBlast                    = NewSpell(49184),
        GlacialAdvance                  = NewSpell(194913),
        PillarOfFrost                   = NewSpell(51271),
        Frostscythe                     = NewSpell(207230),
        HornOfWinter                    = NewSpell(57330),
        EmpowerRuneWeapon               = NewSpell(47568),
        ChillStreak                     = NewSpell(305392),
        FrostwyrmsFury                  = NewSpell(279302),
        BreathOfSindragosa              = NewSpell(1249658),
        ReapersMark                     = NewSpell(439843),

    },
    auras = {
        --Add Auras here
        PillarOfFrost           = 51271,
        UnholyStrength          = 53365,
        BonegrinderFrost        = 377098,
        IcyOnslaught            = 1230273,
        Rime                    = 59052,
        UnleashedFrenzy         = 376907,
        Frostbane               = 1229310,
        Razorice                = 51714,
        IcyTalons               = 194879,
        KillingMachine          = 51124,
        Exterminate             = 441416,
        ReapersMark             = 434765,
        RemorselessWinter       = 196770,
        FrostFever              = 55095,
    },
    talents = {
        --Add Talents here
        PillarOfFrost             = NewSpell(51271),
        GatheringStorm            = NewSpell(194912),
        BitingCold                = NewSpell(377056),
        RageOfTheFrozenChampion   = NewSpell(377076),
        Icebreaker                = NewSpell(392950),
        BindInDarkness            = NewSpell(440031),
        Avalanche                 = NewSpell(207142),
        ArcticAssault             = NewSpell(456230),
        UnleashedFrenzy           = NewSpell(376905),
        IcyTalons                 = NewSpell(435005),
        SmotheringOffense         = NewSpell(435005),
        KillingMachine            = NewSpell(51128),
        Exterminate               = NewSpell(441378),
        ShatteredFrost            = NewSpell(455993),
        ShatteringBlade           = NewSpell(207057),
        AFeastOfSouls             = NewSpell(444072),
        ApocalypseNow             = NewSpell(444040),
        Bonegrinder               = NewSpell(377098),
        CleavingStrikes           = NewSpell(316916),
        ColdHeart                 = NewSpell(281208),
        EnduringStrength          = NewSpell(377190),
        Obliteration              = NewSpell(281238),
        ReaperOfSouls             = NewSpell(440002),
        TheLongWinter             = NewSpell(456240),
        UnholyGround              = NewSpell(374265),
        WitherAway                = NewSpell(441894),
        RidersChampion            = NewSpell(444005),
        Frostbane                 = NewSpell(455993),
        KillingStreak             = NewSpell(1230153),
        FrostboundWill            = NewSpell(51271),
        FrozenDominion            = NewSpell(377226),
        GripOfTheDead             = NewSpell(273952),
        IcyOnslaught              = NewSpell(1230272),
    },
}, "DEATHKNIGHT",2,"Ryan")


